Fixed typo in quotes
hovancik/stretchly pull request #1061
Opened 2021-12-06 18:25 UTC by JoeNibe

### Description of the Change

Fixed a typo in quotes. Changed solder to shoulder

2021-12-11 13:35 UTC, hovancik requested changes

2021-12-11 13:35 UTC, hovancik commented on README.md
> +- Febin Jose, [@JoeNibe](https://github.com/JoeNibe)
this should go at the end of the list

2021-12-16 05:38 UTC, JoeNibe commented on README.md
> +- Febin Jose, [@JoeNibe](https://github.com/JoeNibe)
changes made

2021-12-16 10:23 UTC, hovancik approved these changes

2021-12-16 10:28 UTC, merged