Use code blocks for CLI commands in Readme.md
hovancik/stretchly pull request #1416
Opened 2024-01-06 15:35 UTC by MRDGH2821

Use code blocks for CLI commands

Issue: #

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [ ]  issue was opened to discuss proposed changes before starting implementation. It is important do discuss changes before implementing them (Why should we add it? How should it work? How should it look? Where will it be? ...).
- [ ]  during development, `node` version specified in `package.json` was used (ie using [nvm](https://github.com/creationix/nvm)).
- [ ]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [ ]  app version number was not changed.
- [ ]  all new code has tests to ensure against regressions.
- [ ] `npm run lint` reports no offenses.
- [ ] `npm run test` is error-free.
- [ ]  README and CHANGELOG were updated accordingly.
- [ ]  after PR is approved, all commits in it are [squashed](https://gitbetter.substack.com/p/how-to-squash-git-commits)

### Description of the Change

### Verification Process

### Other information

2024-01-07 13:10 UTC, hovancik requested changes

2024-01-07 13:10 UTC, hovancik commented on README.md
> +See [Application Signing](#application-signing).
can we move this up? 

It is recommended to install Stretchly with Homebrew  (see Application Signing) by running:

2024-01-07 13:10 UTC, hovancik commented on README.md
> +Don't forget to Quit Stretchly, first.
Same here, could be: When upgrading, quit Stretchly and then run:

2024-01-07 14:46 UTC, MRDGH2821 commented
Resolved as requested

2024-01-08 18:13 UTC, hovancik approved these changes
Cheers!

2024-01-08 18:19 UTC, merged

2024-01-09 01:52 UTC, MRDGH2821 commented
Was it code fence or code block ?🤔
Either way, my intent was to make it easier to copy commands.😄

2024-01-09 07:36 UTC, hovancik commented
No idea :D